const sections = [
  {group:'Τομείς PDF',id:'brine-saturation',title:'Brine Saturation',icon:'▤',page:3,desc:'Κορεσμός άλμης και τροφοδοσία προς τον R-201.',purpose:'Παρασκευή κορεσμένης άλμης υψηλής συγκέντρωσης και σταθερή τροφοδοσία προς τον αντιδραστήρα R-201.',properties:['Υψηλή συγκέντρωση άλμης','Σταθερή ροή και πίεση προς R-201','Έλεγχος στάθμης και θερμοκρασίας','Αποφυγή στερεών στην έξοδο']},
  {group:'Τομείς PDF',id:'brine-treatment',title:'Brine Treatment',icon:'◫',page:4,desc:'Κατεργασία άλμης στον R-201.',purpose:'Απομάκρυνση ανεπιθύμητων προσμίξεων από την άλμη πριν από τα επόμενα στάδια.',properties:['Ρύθμιση pH','Κατακρήμνιση ασβεστίου και μαγνησίου','Ελεγχόμενη ανάδευση','Τροφοδοσία προς φίλτρα']},
  {group:'Τομείς PDF',id:'brine-filtration',title:'Brine Filtration',icon:'▥',page:5,desc:'Φίλτρα F-201 A/B και έλεγχοι φιλτραρισμένης άλμης.',purpose:'Φιλτράρισμα της κατεργασμένης άλμης και συγκράτηση στερεών πριν από τη D-203.',properties:['Λειτουργία φίλτρων F-201 A/B','Έλεγχος διαφορικής πίεσης','Απομάκρυνση στερεών','Καθαρή έξοδος προς D-203']},
  {group:'Τομείς PDF',id:'filtered-brine',title:'Filtered Brine Handling',icon:'◩',page:6,desc:'Διαχείριση φιλτραρισμένης άλμης και D-203.',purpose:'Συλλογή και σταθεροποίηση της φιλτραρισμένης άλμης πριν από τον τελικό καθαρισμό.',properties:['Δεξαμενή buffer D-203','Έλεγχος pH','Σταθερή στάθμη','Τροφοδοσία επόμενου σταδίου']},
  {group:'Τομείς PDF',id:'brine-purification',title:'Brine Purification',icon:'◉',page:7,desc:'Καθαρισμός άλμης μέσω C-201A / C-201B.',purpose:'Περαιτέρω καθαρισμός της άλμης με απομάκρυνση ιόντων ασβεστίου και μαγνησίου.',properties:['Στήλες C-201A / C-201B','Μείωση Ca²⁺ και Mg²⁺','Ελεγχόμενη αναγέννηση','Καθαρή έξοδος προς D-204']},
  {group:'Τομείς PDF',id:'pure-brine',title:'Pure Brine Handling',icon:'◧',page:8,desc:'Δεξαμενή καθαρής άλμης D-204 και τροφοδοσία.',purpose:'Αποθήκευση καθαρής άλμης και σταθερή τροφοδοσία του ηλεκτρολύτη.',properties:['Έλεγχος στάθμης D-204','Σταθερή συγκέντρωση','Παρακολούθηση θερμοκρασίας','Ασφαλής τροφοδοσία ηλεκτρολύτη']},
  {group:'Τομείς PDF',id:'electrolyzer',title:'Electrolyzer (CEC)',icon:'ϟ',page:9,desc:'Ηλεκτρολύτης CEC και βασική λειτουργία.',purpose:'Ηλεκτρόλυση καθαρής άλμης για παραγωγή χλωρίου, υδρογόνου και καυστικού διαλύματος.',properties:['Έλεγχος ρεύματος και τάσης','Παραγωγή Cl₂ και H₂','Έλεγχος μεμβρανών','Παρακολούθηση πιέσεων και ροών']},
  {group:'Τομείς PDF',id:'depleted-brine',title:'Depleted Brine Handling',icon:'◫',page:10,desc:'Χημικά απόβλητα άλμης και διαχείριση D-205.',purpose:'Συλλογή και διαχείριση εξαντλημένης άλμης πριν από αποχλωρίωση και ανακύκλωση.',properties:['Buffer D-205','Διαχείριση R-205','Έλεγχος υπολειμματικού χλωρίου','Ροή προς αποχλωρίωση']},
  {group:'Τομείς PDF',id:'dechloration',title:'Brine Dechloration',icon:'◌',page:11,desc:'Φυσική αποχλωρίωση και πύργος C-206.',purpose:'Απομάκρυνση του υπολειμματικού χλωρίου από την εξαντλημένη άλμη.',properties:['Πύργος C-206','Έλεγχος αέρα και κενού','Μείωση ελεύθερου χλωρίου','Ασφαλής έξοδος άλμης']},
  {group:'Τομείς PDF',id:'hypo-synthesis',title:'Hypochlorite Synthesis',icon:'◒',page:12,desc:'Δημιουργία υποχλωριώδους νατρίου.',purpose:'Παραγωγή διαλύματος υποχλωριώδους νατρίου με ελεγχόμενη αντίδραση χλωρίου και καυστικού.',properties:['Έλεγχος αντίδρασης','Ρύθμιση παροχών','Παρακολούθηση θερμοκρασίας','Έλεγχος ενεργού χλωρίνης']},
  {group:'Τομείς PDF',id:'hcl-synthesis',title:'HCl Synthesis',icon:'◉',page:13,desc:'Μονάδα δημιουργίας υδροχλωρικού οξέος.',purpose:'Παραγωγή υδροχλωρικού οξέος μέσω ελεγχόμενης καύσης υδρογόνου και χλωρίου.',properties:['Έλεγχος αναλογίας H₂ / Cl₂','Παρακολούθηση φλόγας','Έλεγχος νερού απορρόφησης','Interlocks και ασφαλής λειτουργία']},
  {group:'Τομείς PDF',id:'hypo-storage',title:'Hypochlorite Storage',icon:'▣',page:16,desc:'Δεξαμενές αποθήκευσης υποχλωριώδους.',purpose:'Αποθήκευση και διάθεση υποχλωριώδους νατρίου από τις δεξαμενές Ζ1–Ζ3 και D1–D3.',properties:['Έλεγχος στάθμης δεξαμενών','Διαχωρισμός αριστερής και δεξιάς πλευράς','Παρακολούθηση χωρητικότητας','Ασφαλής επιλογή δεξαμενής']},
  {group:'Τομείς PDF',id:'sludge',title:'Sludge & Sulphate Treatment',icon:'♨',page:17,desc:'Βοηθητική μονάδα επεξεργασίας λάσπης και θειικών.',purpose:'Συλλογή και επεξεργασία λάσπης και θειικών παραπροϊόντων της μονάδας.',properties:['Διαχείριση R-210','Φίλτρα F-210 A/B','Δεξαμενή D-211','Έλεγχος αντλιών και ροών']},
  {group:'Ξεχωριστή καρτέλα',id:'documents',title:'Έγγραφα & Τρόποι Εκκίνησης Μονάδας',icon:'▧',type:'documents'}
];

const docs = [
 {id:'hcl-start-dcs',title:'Εκκίνηση Υδροχλωρικού από το DCS (από μέσα)',page:14,steps:[
 'Ανοίγω την αντλία υδροχλωρικού P-801A/Β και την βάζω GF και τον ανεμιστήρα Κ-801Α/Β, στην P801 θέλω 1.5 έως 2 bar (PI-8602) και παροχή θέλω από 1.5 έως 2 m³/h.',
 'Κλείνουμε manual την βάνα PIC-2005 για τον υδρογόνο και την PIC-2006 για το χλώριο για να πιάσουμε σωστές πιέσεις προς τον πύργο του υδροχλωρικού.',
 'Αφού πιέσαμε το χλώριο κοντά στο 850 ανοίγουμε την KV8100.','Πατάς HCL UNIT START UP και φυσάει 120 δευτερόλεπτα άζωτο.','Βάζω το νερό 0.350 (FIC-8401).','Σου λέει ο απέξω να ανοίξεις την control του υδρογόνου και την ανοίγεις 35%.','Σου λέει να ανοίξεις την control του χλωρίου και την ανοίγεις στο 45%.','Σου λέει να ανοίξεις τις on/off υδρογόνου και χλωρίου.','Το πιο ασφαλές είναι όταν φτάσεις την βάνα του χλωρίου 60% και του υδρογόνου 45%, αυτός που είναι έξω να κλείσει εντελώς τον αέρα στον πύργο.' ]},
 {id:'hcl-start-outside',title:'Εκκίνηση Υδροχλωρικού Εξωτερικά (βάζεις τη φωτιά)',page:15,steps:['Ανοίγω προς 902.','Ανοίγω το πράσινο βανάκι.','Γεμίζω τα silpot, κλείνω του υδρογόνου όταν βγάλει νερό, και τσεκάρω το demister αν γεμίζει για να κλείσω και του χλωρίου.','Εάν η πίεση στην μεριά του υδρογόνου είναι υψηλή πρέπει να εκτονώσω μέχρι να πάει 400-450 στο silpot του υδρογόνου.','Ανοίγω την κεντρική του υδρογόνου σε συνεννόηση με τον χειριστή μέσα.','Ξεπλένω τα tubes από την μεριά του υδρογόνου και του χλωρίου με περίπου 100-150 λίτρα, σε συνεννόηση με τον χειριστή, για 2 λεπτά.','Ανοίγω την παροχή στο σωληνάκι για την φωτιά και πετάω για λίγο έξω άζωτο ή υδρογόνο για να έρθει το υδρογόνο.','Ανοίγω το πορτάκι και βάζω φωτιά και τοποθετώ το μαρκούτσι μέσα.','Λες στον χειριστή να ανοίξει την control του υδρογόνου 35% και ανοίγεις σιγά σιγά το bypass.','Εφόσον έχεις υδρογόνο και βλέπεις καύση, κλείνεις τις βάνες για το μαρκούτσι και το βγάζεις από τον πύργο.','Λες στον χειριστή να ανοίξει και την control του χλωρίου 45% και ανοίγεις σιγά σιγά το bypass.','Μόλις τερματίσουν οι βάνες, ανοίγονται οι on/off σε συνεννόηση και κλείνουν τα bypass αφού ελεγχθεί η σωστή λειτουργία.','Στο τέλος κλείνεις σιγά σιγά τον αέρα και μετά την χειροκίνητη κάτω.','Βάζεις νερό προσεκτικά από την μεριά του υδρογόνου μέχρι να υπάρχει νερό σε όλη την επιφάνεια της φλόγας.']},
 {id:'hcl-stop-outside',title:'Τρόπος σταματήματος υδροχλωρικού εξωτερικά',page:19,steps:['Ανοίγουμε χειροκίνητες βάνες του αέρα για να αναπνεύσει ο πύργος.','Κλείνουμε την κεντρική του Υδρογόνου.','Ξεπλένουμε με DW την φλόγα ανοίγοντας μία το υδρογόνο και μία το χλώριο.','Κλείνουμε την κεντρική του νερού DW.','Γεμίζουμε τα silpot.','Κλείνουμε την είσοδο νερού Π.Ψ στον μανδύα.','Ανοίγουμε το κενό προς 610.','Γυρνάμε προς 902.','Κλείνω την χειροκίνητη βάνα μπροστά από τις αντλίες (πράσινη βάνα).','Φυσάνε άζωτο στην γραμμή του υδρογόνου.']},
 {id:'hcl-stop-dcs',title:'Τρόπος σταματήματος στο υδροχλωρικό DCS',page:20,steps:['Κάνεις όλα τα interlock disable στον πύργο εκτός από το power failure.','Αρχίζω και κλείνω την FIC-8101 και την FIC-8201 και προσέχω τις πιέσεις PIC-2006 και PIC-2005.','Κατεβάζεις από την FIC-8401 την ροή του νερού.','Ανοίγεις την PIC8300 και την βάζεις Manual στο 50%.','Όταν φτάσει 50% η βάνα του χλωρίου και 35-30% του υδρογόνου πατάμε HCL UNIT SHUTDOWN.','Βγάζω από GF την P801 και την κλείνω, και η βάνα LIC-8501 manual και βάζω στα details Out Lo 0 και Out High 100.']},
 {id:'analysis-naoh',title:'Ανάλυση NaOH & Na₂CO₃ σε διάλυμα',page:21},
 {id:'analysis-chlorine',title:'Ανάλυση ενεργού χλωρίνης',page:22},
 {id:'analysis-d201',title:'Ανάλυση D-201 / D-204 / Feed / Ανωλύτης',page:23},
 {id:'analysis-r201',title:'Ανάλυση R-201 (Ριακτόρας)',page:24},
 {id:'analysis-salt',title:'Ανάλυση αλατιού',page:25}
];

let currentSection = sections[0]; let activeTab='manual'; let currentDoc=docs[0];
const $=s=>document.querySelector(s);
const pageSrc=n=>`assets/pages/page-${String(n).padStart(2,'0')}.webp`;

function buildNav(filter=''){
 const nav=$('#navList');nav.innerHTML='';let last='';
 sections.filter(s=>(s.title+' '+s.desc).toLowerCase().includes(filter.toLowerCase())).forEach(s=>{
  if(s.group!==last){const g=document.createElement('div');g.className='nav-group-title';g.textContent=s.group;nav.append(g);last=s.group}
  const b=document.createElement('button');b.className='nav-item'+(s.id===currentSection.id?' active':'');b.innerHTML=`<span class="nav-icon">${s.icon}</span><span>${s.title}</span>`;b.onclick=()=>selectSection(s);nav.append(b)
 });
}
function selectSection(s){currentSection=s;activeTab=s.type==='documents'?'documents':'manual';$('#pageTitle').textContent=s.title;$('#breadcrumb').textContent=s.type==='documents'?'Βιβλιοθήκη εγγράφων':'Τομείς / '+s.title;renderTabs();renderContent();buildNav($('#searchInput').value);closeSidebar()}
function renderTabs(){const t=$('#tabs');t.innerHTML='';const tabs=currentSection.type==='documents'?[['documents','Έγγραφα & Διαδικασίες'],['additions','Πρόσθετο υλικό']]:[['manual','Επισκόπηση'],['dcs','Εικόνες DCS'],['external','Εξωτερικός Εξοπλισμός'],['additions','Πρόσθετο υλικό']];tabs.forEach(([id,label])=>{const b=document.createElement('button');b.className='tab'+(activeTab===id?' active':'');b.textContent=label;b.onclick=()=>{activeTab=id;renderTabs();renderContent()};t.append(b)})}
async function renderContent(){const c=$('#content'); if(currentSection.type==='documents'&&activeTab==='documents') return renderDocuments(c); if(activeTab==='manual') return renderManual(c); if(activeTab==='dcs') return renderPhotos(c,'dcs'); if(activeTab==='external') return renderPhotos(c,'external'); return renderAdditions(c)}
function renderManual(c){const props=(currentSection.properties||[]).map(x=>`<li>${escapeHtml(x)}</li>`).join('');c.innerHTML=`<div class="hero-title"><div class="big-icon">${currentSection.icon}</div><div><h2>${currentSection.title}</h2><p>${currentSection.desc}</p></div></div><div class="original-badge">🔒 Αυθεντικό περιεχόμενο PDF - μόνο για προβολή</div><div class="overview-layout"><div><div class="image-wrap large-manual"><img class="manual-image zoomable" src="${pageSrc(currentSection.page)}" alt="${currentSection.title}"></div><div class="image-tools"><button class="btn secondary zoom-btn">Μεγέθυνση εικόνας</button></div><section class="description-block"><h3>Περιγραφή</h3><p>${escapeHtml(currentSection.desc)}</p></section></div><div class="info-stack"><section class="info-box purpose"><h3>Σκοπός</h3><p>${escapeHtml(currentSection.purpose||currentSection.desc)}</p></section><section class="info-box properties"><h3>Ιδιότητες</h3><ul>${props}</ul></section></div></div><div id="inlineAdditions"></div>`; bindZoom(c);renderInlineAdditions()}
async function renderPhotos(c,category){const all=await dbGetPhotos(currentSection.id);const photos=all.filter(p=>(p.category||'external')===category);const isDcs=category==='dcs';c.innerHTML=`<div class="section-head-row"><div><h2 class="section-title">${isDcs?'Εικόνες DCS':'Φωτογραφίες εξωτερικού εξοπλισμού'}</h2><p>${isDcs?'Πρόσθεσε επιπλέον οθόνες και σημεία του DCS για αυτόν τον τομέα.':'Πρόσθεσε πραγματικές φωτογραφίες από αντλίες, βάνες, δεξαμενές και άλλο εξωτερικό εξοπλισμό.'}</p></div><button class="btn primary add-photo-here">+ Προσθήκη ${isDcs?'DCS':'εξωτερικής'} φωτογραφίας</button></div><div class="photo-grid large-photos" id="photoGrid"></div>`;renderPhotoGrid(photos,$('#photoGrid'),currentSection.id);c.querySelector('.add-photo-here').onclick=()=>showPhotoDialog(category)}
async function renderAdditions(c){const notes=await dbGetNotes(currentSection.id);const photos=await dbGetPhotos(currentSection.id);c.innerHTML=`<h2 class="section-title">Πρόσθετο υλικό</h2><p>Το υλικό αυτό είναι ξεχωριστό από το PDF και μπορεί να διαγραφεί ή να συμπληρωθεί χωρίς να επηρεαστεί το αρχικό manual.</p><div id="notesList"></div><h3>Εικόνες DCS</h3><div class="photo-grid" id="dcsGrid"></div><h3>Εξωτερικός εξοπλισμός</h3><div class="photo-grid" id="externalGrid"></div>`;renderNotes(notes);renderPhotoGrid(photos.filter(p=>p.category==='dcs'),$('#dcsGrid'));renderPhotoGrid(photos.filter(p=>(p.category||'external')==='external'),$('#externalGrid'))}
function renderDocuments(c){c.innerHTML=`<div class="doc-list"><div class="doc-menu">${docs.map(d=>`<button class="doc-choice ${d.id===currentDoc.id?'active':''}" data-doc="${d.id}">▧ ${d.title}</button>`).join('')}</div><div id="docView"></div></div>`;c.querySelectorAll('.doc-choice').forEach(b=>b.onclick=()=>{currentDoc=docs.find(d=>d.id===b.dataset.doc);renderContent()});renderDocView()}
async function renderDocView(){const v=$('#docView');let body='';if(currentDoc.steps){body=`<div class="original-badge">🔒 Κείμενο από το αρχικό PDF</div><div class="steps">${currentDoc.steps.map((s,i)=>`<label class="step"><input type="checkbox"><span><strong>${i+1}.</strong> ${s}</span></label>`).join('')}</div>`}else{body=`<div class="original-badge">🔒 Αυθεντικό έγγραφο ανάλυσης από το PDF</div><img class="manual-image zoomable" src="${pageSrc(currentDoc.page)}" alt="${currentDoc.title}">`}
 v.innerHTML=`<h2 class="section-title">${currentDoc.title}</h2>${body}<div class="image-tools"><button class="btn secondary show-page">Προβολή αρχικής σελίδας PDF</button></div><div class="additions"><h3>Πρόσθετες σημειώσεις / φωτογραφίες</h3><div id="inlineAdditions"></div></div>`;bindZoom(v);v.querySelector('.show-page').onclick=()=>openImage(pageSrc(currentDoc.page));renderInlineAdditions(currentDoc.id)}
async function renderInlineAdditions(key=currentSection.id){const host=$('#inlineAdditions');if(!host)return;const notes=await dbGetNotes(key),photos=await dbGetPhotos(key);host.innerHTML=`<div id="notesList"></div><div class="photo-grid" id="photoGrid"></div>`;renderNotes(notes,host.querySelector('#notesList'),key);renderPhotoGrid(photos,host.querySelector('#photoGrid'),key)}
function renderNotes(notes,host=$('#notesList'),key=currentSection.id){if(!host)return;host.innerHTML=notes.length?notes.map(n=>`<article class="addition-card"><div class="addition-head"><div><h4>${escapeHtml(n.title)}</h4><p>${escapeHtml(n.body)}</p></div><button class="btn danger delete-note" data-id="${n.id}">Διαγραφή</button></div></article>`).join(''):'<div class="empty-state">Δεν έχει προστεθεί ακόμη πρόσθετο κείμενο.</div>';host.querySelectorAll('.delete-note').forEach(b=>b.onclick=async()=>{await dbDelete('notes',Number(b.dataset.id));renderContent()})}
function renderPhotoGrid(photos,host=$('#photoGrid'),key=currentSection.id){if(!host)return;host.innerHTML=photos.length?photos.map(p=>`<div class="photo-card"><img src="${p.data}" alt="Πρόσθετη φωτογραφία" data-src="${p.data}"><button class="delete-photo" data-id="${p.id}">✕</button></div>`).join(''):'<div class="empty-state">Δεν έχουν προστεθεί φωτογραφίες.</div>';host.querySelectorAll('img').forEach(i=>i.onclick=()=>openImage(i.dataset.src));host.querySelectorAll('.delete-photo').forEach(b=>b.onclick=async()=>{await dbDelete('photos',Number(b.dataset.id));renderContent()})}
function bindZoom(root){root.querySelectorAll('.zoomable').forEach(i=>i.onclick=()=>openImage(i.src));root.querySelectorAll('.zoom-btn').forEach(b=>b.onclick=()=>openImage(root.querySelector('.manual-image').src))}
function openImage(src){$('#fullImage').src=src;$('#imageDialog').showModal()}
function escapeHtml(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function additionKey(){return currentSection.type==='documents'?currentDoc.id:currentSection.id}

const DB='kapachim-manual-db';function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('notes')){const s=d.createObjectStore('notes',{keyPath:'id',autoIncrement:true});s.createIndex('section','section')}if(!d.objectStoreNames.contains('photos')){const s=d.createObjectStore('photos',{keyPath:'id',autoIncrement:true});s.createIndex('section','section')}};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function dbAdd(store,val){const d=await openDB();return new Promise((res,rej)=>{const t=d.transaction(store,'readwrite');t.objectStore(store).add(val);t.oncomplete=res;t.onerror=()=>rej(t.error)})}
async function dbGetBySection(store,section){const d=await openDB();return new Promise((res,rej)=>{const r=d.transaction(store).objectStore(store).index('section').getAll(section);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
const dbGetNotes=s=>dbGetBySection('notes',s);const dbGetPhotos=s=>dbGetBySection('photos',s);
async function dbDelete(store,id){const d=await openDB();return new Promise((res,rej)=>{const t=d.transaction(store,'readwrite');t.objectStore(store).delete(id);t.oncomplete=res;t.onerror=()=>rej(t.error)})}

function showTextDialog(){ $('#noteTitle').value='';$('#noteBody').value='';$('#textDialog').showModal() }
async function saveText(e){e.preventDefault();const title=$('#noteTitle').value.trim(),body=$('#noteBody').value.trim();if(!title||!body)return;await dbAdd('notes',{section:additionKey(),title,body,createdAt:Date.now()});$('#textDialog').close();renderContent()}
function showPhotoDialog(category='external'){ $('#photoCategory').value=category; $('#photoFiles').value=''; $('#photoDialog').showModal() }
async function handlePhotos(files,category){for(const f of files){if(!f.type.startsWith('image/'))continue;const data=await compressImage(f);await dbAdd('photos',{section:additionKey(),category,data,name:f.name,createdAt:Date.now()})}$('#photoDialog').close();renderContent()}
function compressImage(file){return new Promise((res,rej)=>{const r=new FileReader();r.onerror=rej;r.onload=()=>{const im=new Image();im.onload=()=>{const max=1600,scale=Math.min(1,max/Math.max(im.width,im.height));const cv=document.createElement('canvas');cv.width=Math.round(im.width*scale);cv.height=Math.round(im.height*scale);cv.getContext('2d').drawImage(im,0,0,cv.width,cv.height);res(cv.toDataURL('image/jpeg',.82))};im.src=r.result};r.readAsDataURL(file)})}
function closeSidebar(){$('#sidebar').classList.remove('open');$('#backdrop').classList.remove('show')}

$('#searchInput').oninput=e=>buildNav(e.target.value);$('#openSidebar').onclick=()=>{$('#sidebar').classList.add('open');$('#backdrop').classList.add('show')};$('#closeSidebar').onclick=closeSidebar;$('#backdrop').onclick=closeSidebar;$('#addTextTop').onclick=showTextDialog;$('#addTextSide').onclick=showTextDialog;$('#textForm').onsubmit=saveText;$('#addPhotoTop').onclick=()=>showPhotoDialog('external');$('#addPhotoSide').onclick=()=>showPhotoDialog('external');$('#photoForm').onsubmit=async e=>{e.preventDefault();await handlePhotos([...$('#photoFiles').files],$('#photoCategory').value)};$('#closeImage').onclick=()=>$('#imageDialog').close();$('#openOriginal').onclick=()=>window.open('original-manual.pdf','_blank');
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
buildNav();selectSection(sections[0]);
